name: 🤯 バグ・不具合修正
description: バグなどの不具合を修正する際に使用します
title: "タイトルを入力してください"
labels: ["バグ・不具合修正"]
body:
  - type: textarea
    id: bug_details
    attributes:
      label: 詳細
      description: 内容の詳細を自由に記述してください
      placeholder: ここに詳細を入力
    validations:
      required: true
