name: 🤯 バグ・不具合修正
description: バグなどの不具合を修正する際に使用します
title: "[BugFix] タイトルを入力してください"
labels: ["バグ・不具合修正"]
body:
  - type: input
    id: bug_title
    attributes:
      label: タイトル
      description: 不具合の内容を簡潔に書いてください
      placeholder: 例）ログイン時にエラーが発生する
    validations:
      required: true

  - type: textarea
    id: bug_details
    attributes:
      label: 詳細
      description: 発生手順やスクリーンショット、エラーメッセージなど
      placeholder: 手順や再現方法を記載
    validations:
      required: true

  - type: textarea
    id: bug_note
    attributes:
      label: 備考
      description: 関連Issue、優先度、その他特記事項があれば記入してください
      placeholder: 例）関連するIssue番号や優先度
    validations:
      required: false
