name: 📝 変更・改善
description: 変更や改善が必要な場合に使用します
title: "タイトルを入力してください"
labels: ["改善"]
body:
  - type: textarea
    id: improve_details
    attributes:
      label: 詳細
      description: 内容の詳細を自由に記述してください
      placeholder: ここに詳細を入力
    validations:
      required: true
