name: 📝 改善
description: 不具合などではないが、何か改善が必要な場合に使用します
title: "タイトルを入力してください"
labels: ["改善"]
body:
  - type: input
    id: improve_title
    attributes:
      label: タイトル
      description: どのような改善かを簡潔に書いてください
      placeholder: 例）ナビゲーションのレスポンス改善
    validations:
      required: true

  - type: textarea
    id: improve_details
    attributes:
      label: 詳細
      description: 背景、目的、期待される効果などを書いてください
      placeholder: 例）ユーザーが迷わないように導線を明確にしたい
    validations:
      required: true

  - type: textarea
    id: improve_note
    attributes:
      label: 備考
      description: 補足情報や関連Issueがあれば記入してください
      placeholder: "関連Issue: #456"
    validations:
      required: false
