name: タスク報告
description: タスクや作業内容の報告用テンプレート
title: タイトルを入力してください
labels: ["report"]
body:
  - type: input
    id: title_input
    attributes:
      label: タイトル
      description: 何をしたのかをできるだけ具体的に書いてください
      placeholder: 例）APIエンドポイントのバグ修正
    validations:
      required: true

  - type: textarea
    id: remarks
    attributes:
      label: 備考
      description: その他に記録しておきたいことがあれば記入してください
      placeholder: 例）関連Issueや背景情報など
    validations:
      required: false
