name: ­ЪњА Тќ░УдЈУ┐йтіа
description: сЃџсЃ╝сѓИсѓёсѓ│сЃ│сЃЮсЃ╝сЃЇсЃ│сЃѕсђЂТЕЪУЃйсЂ«Тќ░УдЈУ┐йтіасѓњУАїсЂєжџЏсЂФСй┐ућесЂЌсЂЙсЂЎ
title: сѓ┐сѓцсЃѕсЃФсѓњтЁЦтіЏсЂЌсЂдсЂЈсЂасЂЋсЂё
labels: ["Тќ░УдЈУ┐йтіа"]
body:
  - type: textarea
    id: remarks
    attributes:
      label: тѓЎУђЃ
      description: сЂЮсЂ«С╗ќтѓЎУђЃсЂфсЂЕсЂїсЂѓсѓїсЂ░УеўтЁЦсЂЌсЂдсЂЈсЂасЂЋсЂё
      placeholder: СЙІ№╝ЅжќбжђБIssueсѓёУЃїТЎ»ТЃЁта▒сЂфсЂЕ
    validations:
      required: false
