name: 💡 新規追加
description: ページやコンポーネント、機能の新規追加を行う際に使用します
title: タイトルを入力してください
labels: ["新規追加"]
body:
  - type: textarea
    id: remarks
    attributes:
      label: 詳細
      description: 内容の詳細を自由に記述してください
      placeholder: ここに詳細を入力
    validations:
      required: false
